
maroon5 = Artist.create(name: "Maroon 5")
lady_gaga = Artist.create(name: "Lady Gaga")
christina_aguilera = Artist.create(name: "Christina Aguilera")
bruno_mars = Artist.create(name: "Bruno Mars")
pearl_jam = Artist.create(name: "Pearl Jam")
pink_floyd = Artist.create(name: "Pink Floyd")
nirvana = Artist.create(name: "Nirvana")
ac_dc = Artist.create(name: "AC/DC")
led_zeppelin = Artist.create(name: "Led Zeppelin")
calvin_harris = Artist.create(name: "Calvin Harris")
kaskade = Artist.create(name: "Kaskade")
flume = Artist.create(name: "Flume")
skrillex = Artist.create(name: "Skrillex")
above_and_beyond = Artist.create(name: "Above & Beyond")
lil_wayne = Artist.create(name: "Lil Wayne")
mac_miller = Artist.create(name: "Mac Miller")
2_chainz = Artist.create(name: "2 Chainz")
eminem = Artist.create(name: "Eminem")
travis_scott = Artist.create(name: "Travis Scott")
dixie_chicks = Artist.create(name: "Dixie Chicks")
johnny_cash = Artist.create(name: "Johnny Cash")
dolly_parton = Artist.create(name: "Dolly Parton")
keith_urban = Artist.create(name: "Keith Urban")
kenny_chesney = Artist.create(name: "Kenny Chesney")



